
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team01-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team01-m23-10am-1
pull_requests: [{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"Zixiao-University","number":18,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-1/pull/18"},{"author":{"id":"U_kgDOBnGf2A","is_bot":false,"login":"marcushuang1","name":""},"headRefName":"Ziyang-PublicHoliday","number":17,"title":"Add PublicHoliday Service and Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-1/pull/17"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-HomeController","number":16,"title":"Add Home Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-1/pull/16"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-ZipCode","number":15,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-1/pull/15"}]
